---
title: "Gov 50 Final Project"
author: "Peter Jones"
description: "Separatist Region Recognition"
output:
  distill::distill_article:
    self_contained: false
---

#Proposal

Does freedom of expression and association under a state's central government affect the likelihood that it will have to make autonomy concessions to self-determination movements? In this study, I seek to gain a deeper understanding of the conditions under which self-determination movements (SDMs) in pursuit of sovereignty are more likely to succeed in gaining autonomy concessions from their central governments. It strikes me that a free civil society (for which I will use free-association and -press index scores across times) may serve as a double-edged sword in the context of SDM success. On the one hand, more democratized flow of information likely makes it easier for separatist agents to mobilize, coordinate, and put their ideas into action. On the other hand, repressed civil societies raise the costs of inaction to SDM participants and may therefore incentivize more extreme tactics that are more likely to extract concessions from central governments. My hypothesis is that freer civil societies are more conducive to central government concessions, most likely because there are lesser audience costs in repressive autocracies. 

The explanatory variables I anticipate analyzing across individual SDMs that make sovereignty declarations — those being my unit of analysis — are their central government's press freedom and assembly freedom index scores at the onset of the conflict (as determined by Reporters Sans Frontieres), and whether or not separatists employed violence. My outcome variable of interest is whether or not the central government made either an "autonomy" concession or an "independence" concession. 

I will use a couple available datasets to conduct this analysis. The most important one is Nicholas Sambanis's, Micha Germann's, and Andreas Schädel's 2018 dataset on Self-Determination Movements from the Journal of Conflict Resolution. This dataset contains every movement between 1945 and 2012 that fits the defintion of "movements by one or more political organizations that are connected to an ethnic group and make claims for increased SD from the state." This set contains binary variables for concessions and violence, as well as the dates of the movement, and whether or not it made a sovereignty declaration. I will then use Reporters Sans Frontieres' press freedom index, which it has published since 2002, to extract the press and assembly freedom index scores. While I hope to find some kind of proxy measure for movements between 1945 and 2002, I may just have to make it an analysis of the final decade of the Sambanis data, which I am comfortable with.

A result indicating that SDMs in freer civil societies are less likely to succeed would counter my hypothesis; the converse would confirm it. I am hoping that the breadth of data is wide enough such that I can control for factors like geography and GDP as well; if possible, this would make me more confident in the final result of my analysis.














